//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Blog_id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string ResimUrl { get; set; }
        public Nullable<int> Kategori_id { get; set; }
        public string AltBaslik { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
